FROM node:latest as build
WORKDIR /app
COPY . .
ARG VITE_INSTANCE_URL
ARG VITE_SERVER_URL
ARG VITE_DEMO_MODE
RUN VITE_INSTANCE_URL=$VITE_INSTANCE_URL VITE_SERVER_URL=$VITE_SERVER_URL
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
